---
new_page_extension: md
auto_deploy: false
admin_path: "/src/admin"
webhook_url: 
sections:
- type: heading
  label: English
- type: directory
  path: src/en
  label: Root/
  create: all
  match: "**/*"
  templates:
  - post
- type: document
  path: src/en/index.njk
  label: Home
- type: document
  path: src/en/now.md
  label: Now
- type: document
  path: src/contacts.md
  label: Contacts
- type: directory
  path: src/blog
  label: Blog/
  create: documents
  match: "*.md"
- type: directory
  path: src/code
  label: Code/
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: src/en/speeches
  label: Speeches/
  create: documents
  match: "*.md"
  templates:
  - post
- type: heading
  label: Russian
- type: directory
  path: src/ru
  label: Root
  create: all
  match: "**/*"
  templates:
  - post
- type: heading
  label: All
- type: directory
  path: src
  label: Content
  create: all
  match: "**/*"
  templates:
  - post
upload_dir: src/assets/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run serve
